#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 2.1

executors:
  daml-executor:
    docker:
      - image: digitalasset/daml-sdk:0.12.1-circleci-master


jobs:
  daml_test:
    executor: daml-executor
    steps:
      - checkout
      - run:
          command: |
            mkdir -p target/daml-test-reports
            da compile
            da run -- damlc test --junit target/daml-test-reports/daml-test.xml daml/DA/RefApps/StructuredTradeFinance/Main.daml
      - store_test_results:
          path: target/daml-test-reports
      - store_artifacts:
          path: target/daml-test-reports
      - run:
          name: Run Blackduck Detect
          command: |
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) ci-build digitalasset_ex-structured-trade-finance master --logging.level.com.synopsys.integration=DEBUG

workflows:
  version: 2
  build_and_test:
    jobs:
      - daml_test:
          context: blackduck
